// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dgcmatrix_row_scale
Eigen::MatrixXd dgcmatrix_row_scale(Eigen::Map<Eigen::SparseMatrix<double>> mat, bool scale, bool center, double scale_max);
RcppExport SEXP _Eula_matrix_dgcmatrix_row_scale(SEXP matSEXP, SEXP scaleSEXP, SEXP centerSEXP, SEXP scale_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< double >::type scale_max(scale_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_row_scale(mat, scale, center, scale_max));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_row_scale2
Eigen::MatrixXd dgcmatrix_row_scale2(Eigen::Map<Eigen::SparseMatrix<double>> mat, std::vector<double>& mu, std::vector<double>& sigma, bool scale, bool center, double scale_max);
RcppExport SEXP _Eula_matrix_dgcmatrix_row_scale2(SEXP matSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP scaleSEXP, SEXP centerSEXP, SEXP scale_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< double >::type scale_max(scale_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_row_scale2(mat, mu, sigma, scale, center, scale_max));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_std_rowvar
std::vector<double> dgcmatrix_std_rowvar(Eigen::Map<Eigen::SparseMatrix<double>> mat, std::vector<double>& mu, std::vector<double>& sd, double clip);
RcppExport SEXP _Eula_matrix_dgcmatrix_std_rowvar(SEXP matSEXP, SEXP muSEXP, SEXP sdSEXP, SEXP clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type clip(clipSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_std_rowvar(mat, mu, sd, clip));
    return rcpp_result_gen;
END_RCPP
}
// matrix_std_rowvar
std::vector<double> matrix_std_rowvar(Eigen::Map<Eigen::MatrixXd> mat, std::vector<double>& mu, std::vector<double>& sd, double clip);
RcppExport SEXP _Eula_matrix_matrix_std_rowvar(SEXP matSEXP, SEXP muSEXP, SEXP sdSEXP, SEXP clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type clip(clipSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_std_rowvar(mat, mu, sd, clip));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_log_norm
Eigen::SparseMatrix<double> dgcmatrix_log_norm(Eigen::SparseMatrix<double> data, const std::vector<double>& scale_factor);
RcppExport SEXP _Eula_matrix_dgcmatrix_log_norm(SEXP dataSEXP, SEXP scale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type scale_factor(scale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_log_norm(data, scale_factor));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_rc_norm
Eigen::SparseMatrix<double> dgcmatrix_rc_norm(Eigen::SparseMatrix<double> data, const std::vector<double>& scale_factor);
RcppExport SEXP _Eula_matrix_dgcmatrix_rc_norm(SEXP dataSEXP, SEXP scale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type scale_factor(scale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_rc_norm(data, scale_factor));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_clr_norm
Eigen::SparseMatrix<double> dgcmatrix_clr_norm(Eigen::SparseMatrix<double> data);
RcppExport SEXP _Eula_matrix_dgcmatrix_clr_norm(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_clr_norm(data));
    return rcpp_result_gen;
END_RCPP
}
// matrix_log_norm
Eigen::MatrixXd matrix_log_norm(Eigen::MatrixXd data, const std::vector<double>& scale_factor);
RcppExport SEXP _Eula_matrix_matrix_log_norm(SEXP dataSEXP, SEXP scale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type scale_factor(scale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_log_norm(data, scale_factor));
    return rcpp_result_gen;
END_RCPP
}
// matrix_rc_norm
Eigen::MatrixXd matrix_rc_norm(Eigen::MatrixXd data, const std::vector<double>& scale_factor);
RcppExport SEXP _Eula_matrix_matrix_rc_norm(SEXP dataSEXP, SEXP scale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type scale_factor(scale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_rc_norm(data, scale_factor));
    return rcpp_result_gen;
END_RCPP
}
// matrix_clr_norm
Eigen::MatrixXd matrix_clr_norm(Eigen::MatrixXd data);
RcppExport SEXP _Eula_matrix_matrix_clr_norm(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_clr_norm(data));
    return rcpp_result_gen;
END_RCPP
}
// matrix_column_standardize
Eigen::MatrixXd matrix_column_standardize(Eigen::MatrixXd data);
RcppExport SEXP _Eula_matrix_matrix_column_standardize(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_column_standardize(data));
    return rcpp_result_gen;
END_RCPP
}
// matrix_l2norm
Eigen::MatrixXd matrix_l2norm(Eigen::MatrixXd data, uint32_t margin);
RcppExport SEXP _Eula_matrix_matrix_l2norm(SEXP dataSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type data(dataSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type margin(marginSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_l2norm(data, margin));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_l2norm
Eigen::SparseMatrix<double> dgcmatrix_l2norm(Eigen::SparseMatrix<double> data, uint32_t margin);
RcppExport SEXP _Eula_matrix_dgcmatrix_l2norm(SEXP dataSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type margin(marginSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_l2norm(data, margin));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_rowsums
std::vector<double> dgcmatrix_rowsums(Eigen::Map<Eigen::SparseMatrix<double>> mat);
RcppExport SEXP _Eula_matrix_dgcmatrix_rowsums(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_rowsums(mat));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_rowmeans
std::vector<double> dgcmatrix_rowmeans(Eigen::Map<Eigen::SparseMatrix<double>> mat);
RcppExport SEXP _Eula_matrix_dgcmatrix_rowmeans(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_rowmeans(mat));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_rowvars_know_means
std::vector<double> dgcmatrix_rowvars_know_means(Eigen::Map<Eigen::SparseMatrix<double>> mat, const std::vector<double>& mu);
RcppExport SEXP _Eula_matrix_dgcmatrix_rowvars_know_means(SEXP matSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_rowvars_know_means(mat, mu));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_rowvars
std::vector<double> dgcmatrix_rowvars(Eigen::Map<Eigen::SparseMatrix<double>> mat);
RcppExport SEXP _Eula_matrix_dgcmatrix_rowvars(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_rowvars(mat));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_rowmeans_expm1
std::vector<double> dgcmatrix_rowmeans_expm1(Eigen::Map<Eigen::SparseMatrix<double>> mat);
RcppExport SEXP _Eula_matrix_dgcmatrix_rowmeans_expm1(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_rowmeans_expm1(mat));
    return rcpp_result_gen;
END_RCPP
}
// matrix_rowmeans_expm1
std::vector<double> matrix_rowmeans_expm1(Eigen::Map<Eigen::MatrixXd> mat);
RcppExport SEXP _Eula_matrix_matrix_rowmeans_expm1(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_rowmeans_expm1(mat));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_rowvars_expm1_know_means
std::vector<double> dgcmatrix_rowvars_expm1_know_means(Eigen::Map<Eigen::SparseMatrix<double>> mat, const std::vector<double>& mu);
RcppExport SEXP _Eula_matrix_dgcmatrix_rowvars_expm1_know_means(SEXP matSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_rowvars_expm1_know_means(mat, mu));
    return rcpp_result_gen;
END_RCPP
}
// dgcmatrix_rowvars_expm1
std::vector<double> dgcmatrix_rowvars_expm1(Eigen::Map<Eigen::SparseMatrix<double>> mat);
RcppExport SEXP _Eula_matrix_dgcmatrix_rowvars_expm1(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::SparseMatrix<double>> >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(dgcmatrix_rowvars_expm1(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Eula_matrix_dgcmatrix_row_scale", (DL_FUNC) &_Eula_matrix_dgcmatrix_row_scale, 4},
    {"_Eula_matrix_dgcmatrix_row_scale2", (DL_FUNC) &_Eula_matrix_dgcmatrix_row_scale2, 6},
    {"_Eula_matrix_dgcmatrix_std_rowvar", (DL_FUNC) &_Eula_matrix_dgcmatrix_std_rowvar, 4},
    {"_Eula_matrix_matrix_std_rowvar", (DL_FUNC) &_Eula_matrix_matrix_std_rowvar, 4},
    {"_Eula_matrix_dgcmatrix_log_norm", (DL_FUNC) &_Eula_matrix_dgcmatrix_log_norm, 2},
    {"_Eula_matrix_dgcmatrix_rc_norm", (DL_FUNC) &_Eula_matrix_dgcmatrix_rc_norm, 2},
    {"_Eula_matrix_dgcmatrix_clr_norm", (DL_FUNC) &_Eula_matrix_dgcmatrix_clr_norm, 1},
    {"_Eula_matrix_matrix_log_norm", (DL_FUNC) &_Eula_matrix_matrix_log_norm, 2},
    {"_Eula_matrix_matrix_rc_norm", (DL_FUNC) &_Eula_matrix_matrix_rc_norm, 2},
    {"_Eula_matrix_matrix_clr_norm", (DL_FUNC) &_Eula_matrix_matrix_clr_norm, 1},
    {"_Eula_matrix_matrix_column_standardize", (DL_FUNC) &_Eula_matrix_matrix_column_standardize, 1},
    {"_Eula_matrix_matrix_l2norm", (DL_FUNC) &_Eula_matrix_matrix_l2norm, 2},
    {"_Eula_matrix_dgcmatrix_l2norm", (DL_FUNC) &_Eula_matrix_dgcmatrix_l2norm, 2},
    {"_Eula_matrix_dgcmatrix_rowsums", (DL_FUNC) &_Eula_matrix_dgcmatrix_rowsums, 1},
    {"_Eula_matrix_dgcmatrix_rowmeans", (DL_FUNC) &_Eula_matrix_dgcmatrix_rowmeans, 1},
    {"_Eula_matrix_dgcmatrix_rowvars_know_means", (DL_FUNC) &_Eula_matrix_dgcmatrix_rowvars_know_means, 2},
    {"_Eula_matrix_dgcmatrix_rowvars", (DL_FUNC) &_Eula_matrix_dgcmatrix_rowvars, 1},
    {"_Eula_matrix_dgcmatrix_rowmeans_expm1", (DL_FUNC) &_Eula_matrix_dgcmatrix_rowmeans_expm1, 1},
    {"_Eula_matrix_matrix_rowmeans_expm1", (DL_FUNC) &_Eula_matrix_matrix_rowmeans_expm1, 1},
    {"_Eula_matrix_dgcmatrix_rowvars_expm1_know_means", (DL_FUNC) &_Eula_matrix_dgcmatrix_rowvars_expm1_know_means, 2},
    {"_Eula_matrix_dgcmatrix_rowvars_expm1", (DL_FUNC) &_Eula_matrix_dgcmatrix_rowvars_expm1, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Eula_matrix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
