# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgcmatrix_row_scale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10) {
    .Call('_Eula_matrix_dgcmatrix_row_scale', PACKAGE = 'Eula.matrix', mat, scale, center, scale_max)
}

dgcmatrix_row_scale2 <- function(mat, mu, sigma, scale = TRUE, center = TRUE, scale_max = 10) {
    .Call('_Eula_matrix_dgcmatrix_row_scale2', PACKAGE = 'Eula.matrix', mat, mu, sigma, scale, center, scale_max)
}

dgcmatrix_std_rowvar <- function(mat, mu, sd, clip) {
    .Call('_Eula_matrix_dgcmatrix_std_rowvar', PACKAGE = 'Eula.matrix', mat, mu, sd, clip)
}

matrix_std_rowvar <- function(mat, mu, sd, clip) {
    .Call('_Eula_matrix_matrix_std_rowvar', PACKAGE = 'Eula.matrix', mat, mu, sd, clip)
}

dgcmatrix_log_norm <- function(data, scale_factor) {
    .Call('_Eula_matrix_dgcmatrix_log_norm', PACKAGE = 'Eula.matrix', data, scale_factor)
}

dgcmatrix_rc_norm <- function(data, scale_factor) {
    .Call('_Eula_matrix_dgcmatrix_rc_norm', PACKAGE = 'Eula.matrix', data, scale_factor)
}

dgcmatrix_clr_norm <- function(data) {
    .Call('_Eula_matrix_dgcmatrix_clr_norm', PACKAGE = 'Eula.matrix', data)
}

matrix_log_norm <- function(data, scale_factor) {
    .Call('_Eula_matrix_matrix_log_norm', PACKAGE = 'Eula.matrix', data, scale_factor)
}

matrix_rc_norm <- function(data, scale_factor) {
    .Call('_Eula_matrix_matrix_rc_norm', PACKAGE = 'Eula.matrix', data, scale_factor)
}

matrix_clr_norm <- function(data) {
    .Call('_Eula_matrix_matrix_clr_norm', PACKAGE = 'Eula.matrix', data)
}

matrix_column_standardize <- function(data) {
    .Call('_Eula_matrix_matrix_column_standardize', PACKAGE = 'Eula.matrix', data)
}

matrix_l2norm <- function(data, margin) {
    .Call('_Eula_matrix_matrix_l2norm', PACKAGE = 'Eula.matrix', data, margin)
}

dgcmatrix_l2norm <- function(data, margin) {
    .Call('_Eula_matrix_dgcmatrix_l2norm', PACKAGE = 'Eula.matrix', data, margin)
}

dgcmatrix_rowsums <- function(mat) {
    .Call('_Eula_matrix_dgcmatrix_rowsums', PACKAGE = 'Eula.matrix', mat)
}

dgcmatrix_rowmeans <- function(mat) {
    .Call('_Eula_matrix_dgcmatrix_rowmeans', PACKAGE = 'Eula.matrix', mat)
}

dgcmatrix_rowvars_know_means <- function(mat, mu) {
    .Call('_Eula_matrix_dgcmatrix_rowvars_know_means', PACKAGE = 'Eula.matrix', mat, mu)
}

dgcmatrix_rowvars <- function(mat) {
    .Call('_Eula_matrix_dgcmatrix_rowvars', PACKAGE = 'Eula.matrix', mat)
}

dgcmatrix_rowmeans_expm1 <- function(mat) {
    .Call('_Eula_matrix_dgcmatrix_rowmeans_expm1', PACKAGE = 'Eula.matrix', mat)
}

matrix_rowmeans_expm1 <- function(mat) {
    .Call('_Eula_matrix_matrix_rowmeans_expm1', PACKAGE = 'Eula.matrix', mat)
}

dgcmatrix_rowvars_expm1_know_means <- function(mat, mu) {
    .Call('_Eula_matrix_dgcmatrix_rowvars_expm1_know_means', PACKAGE = 'Eula.matrix', mat, mu)
}

dgcmatrix_rowvars_expm1 <- function(mat) {
    .Call('_Eula_matrix_dgcmatrix_rowvars_expm1', PACKAGE = 'Eula.matrix', mat)
}

